FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH=/opt/program 

WORKDIR /opt/program

RUN pip install --no-cache-dir pandas scikit-learn skops flask

COPY src ./src

EXPOSE 8080

CMD [ "python", "-m", "src.sagemaker_inference" ]
