FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH=/opt/program 

WORKDIR /opt/program

RUN pip install --no-cache-dir pandas scikit-learn skops flask

COPY src ./src
COPY docker/serve /usr/local/bin/serve

RUN chmod +x /usr/local/bin/serve

EXPOSE 8080

ENTRYPOINT ["/usr/local/bin/serve"]
CMD ["serve"]
