stages:
  train:
    cmd: python -m src.train
    deps:
      - src/train.py
      - src/data_loader.py
      - src/features.py
      - src/data/penguins.csv
    outs:
      - model_artifacts/penguin_classifier_model.pkl
      - model_artifacts/model_metadata.json
      - model_artifacts/feature_names.json
      - model_artifacts/test_predictions.csv

  evaluate:
    cmd: python -m src.evaluate
    deps:
      - src/evaluate.py
      - src/data_loader.py
      - src/data/penguins.csv
      - model_artifacts/penguin_classifier_model.pkl
    metrics:
      - model_artifacts/metrics.json
